### PR TITLE
Render links as text only, ignoring URL

### LINKED ISSUE #4: Bug: hyperlinked header breaks TOC formatting
Adding a hyperlink to a header:

```md
## [Example](https://example.com/)
```

Will lead to the generated TOC being funky:

```md
- [[Example](https://example.com/)](#examplehttpsexamplecom)
```

Here's how it renders:

screenshot of TOC

The correct generation of the TOC should look like:

```md
- [[Example](https://example.com/)](#example)
```

### PR DESCRIPTION
**Pull request by stefanv**
Closes #4

(Needed for https://github.com/scientific-python/spin/pull/234/files)

### CODE REVIEW

**Comment by stefanv** [comment]
I also suppressed a warning that arose from BeautifulSoup.

**Comment by stefanv** [comment]
I only tested this on GitHub. Would be worth checking what gitlab does with links in headers.

**Comment by stefanv** [comment]
@jsh9 Is this project actively monitored?

**Comment by jsh9** [comment]
> @jsh9 Is this project actively monitored?

Hi @stefanv , thank you for opening up this PR, and sorry for the delay.  Let me take a look at it.

**Comment by jsh9** [comment]
Everything looks good to me.  Thank you again @stefanv !

I've published the new version on PyPI.

**Comment by stefanv** [comment]
No worries for the delay @jsh9, I was mainly trying to establish whether I needed to pin against my fork, or whether this one is still in motion. Thanks for the review and merge!

**Pull request merged**
